In [1]:
#4
import numpy as np

A = np.array([[3, -1, 2],
              [-2, 4, 0]])

B = np.array([[2, 0],
              [-1, 4],
              [-3, 2]])

result = np.dot(A, B)

print(result)

[[ 1  0]
 [-8 16]]


In [2]:
#7
import numpy as np

A = np.array([[3, -1, 2],
              [-2, 4, 0]])

B = np.array([[2, 0],
              [-1, 4],
              [-3, 2]])

result = np.dot(B, A)

print(result)

[[  6  -2   4]
 [-11  17  -2]
 [-13  11  -6]]


In [6]:
#12
import numpy as np

A = np.array([[3, -2, 5],
              [0, -1, 6],
              [-4, 2, -1]])

B = np.array([[2, -1, 0],
              [3, -5, 2],
              [1, 4, -2]])

result = np.dot(B, A)

print(result)

[[  6  -3   4]
 [  1   3 -17]
 [ 11 -10  31]]
